# Numpy: Basic array operation

*Here we covered all the basic about numpy, specially about basic array ooperations 





In [2]:
import numpy as np

#### One dimensional array


In [3]:
a = np.array([5,6,9])

In [4]:
a[0]

5

In [5]:
a[1]

6

In [6]:
# Array dimension
a.ndim

1

#### Two dimansional Array

In [7]:
b = np.array([[1,2], [3,4],[5,6]])

In [8]:
# Array dimension
b.ndim

2

In [9]:
# Item size (in byte)
b.itemsize

8

In [10]:
# Data type
b.dtype

dtype('int64')

In [11]:
# Predefine the array type (float for this example)
b = np.array([[1,2], [3,4],[5,6]], dtype=np.float64)

In [13]:
# Data type
b.dtype

dtype('float64')

In [15]:
# Print the array
b

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [16]:
# Array Size (number elements)
b.size

6

In [17]:
# Array Shape (type of matrix)
b.shape

(3, 2)

In [18]:
# Predefine the array type (Complexe numbers for this example)
b = np.array([[1,2], [3,4],[5,6]], dtype=complex)

In [19]:
# Print the array
b

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

#### Creating array with placeholder numbers

In [20]:
# Creating array with 0 placeholder numbers
c = np.zeros( (3,4) )

In [21]:
# Print the array
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
# Creating array with 1 placeholder numbers
c = np.ones( (3,3) )

In [23]:
# Print the array
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### Creating array with range of numbers

In [25]:
# Creating array with range 
d = np.arange(1,5)

In [26]:
# Print the array
d

array([1, 2, 3, 4])

In [27]:
# Creating array with range wiht step
d = np.arange(1,5,2)

In [28]:
# Print the array
d

array([1, 3])

In [29]:
# Creating array with range wiht linear spacing
d = np.linspace(1,5,10)

In [30]:
# Print the array
d

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

#### Reshape arrays

In [31]:
e = np.array([[1,2], [3,4],[5,6]])

In [32]:
# Print the array
e

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
# The shape of the array
e.shape

(3, 2)

In [38]:
# ReShape the array 
e.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
# ReShape the array 
e.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [42]:
# Flattering array
e.ravel()

array([1, 2, 3, 4, 5, 6])

## Mathematical Operations in Numpy

In [44]:
a = np.array([[1,2], [3,4],[5,6]])

In [46]:
# The minimum in Array
a.min()

1

In [47]:
# The maximum in array
a.max()

6

In [48]:
# Sum all the numbers in array
a.sum()

21

In [49]:
# Sum all the number in the axix 0 (top to bottom)
a.sum(axis=0)

array([ 9, 12])

In [50]:
# Sum all the number in the axix 1 (left to right)
a.sum(axis=1)

array([ 3,  7, 11])

In [51]:
# Square of each elements
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [ ]:
# Create two new arrays

In [52]:
a = np.array([[1,2], [3,4]])

In [53]:
b = np.array([[5,6],[7,8]])

In [54]:
# Print Array
a

array([[1, 2],
       [3, 4]])

In [55]:
# Print Array
b

array([[5, 6],
       [7, 8]])

In [57]:
# Sum of arrays
a+b

array([[ 6,  8],
       [10, 12]])

In [58]:
# Multiplication of arrays
a*b

array([[ 5, 12],
       [21, 32]])

In [59]:
# Division of arrays
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [60]:
# Matrix Product of array
a.dot(b)

array([[19, 22],
       [43, 50]])